services:
  lb:
    image: haproxy:2.9-alpine
    container_name: lb
    ports:
      - "8080:80"
      - "8404:8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: nginx:alpine
    container_name: app1
    volumes:
      - ./backends/app1.conf:/etc/nginx/conf.d/default.conf:ro

  app2:
    image: nginx:alpine
    container_name: app2
    volumes:
      - ./backends/app2.conf:/etc/nginx/conf.d/default.conf:ro

  app3:
    image: nginx:alpine
    container_name: app3
    volumes:
      - ./backends/app3.conf:/etc/nginx/conf.d/default.conf:ro